@startuml Diagrama de classes Nextar Backoffice


Store -- Invoice

class Store{
    Guid Id
    bool Active
    string Email        
    DateTime RegistredAt    
    Invoice[] Invoices
}

class Invoice{
    Guid Id
    DateTime RegistredAt
    DateTime PaiedAt
    DateTime ExpirationAt
    Decimal Amount
}
@enduml